# Operating system.
os_name: macos

# Detector type. Current options: mtcnn, mediapipe
detector_type: mediapipe

# Fragments number of squares.
squares_height: 120
squares_width: 80

# Fragments: do we shift faces over time?
shift_landmarks: False

# Display shape.
display_width: 768
display_height: 1366
rotation: 90

# Face crop features.
pupil_left: 5
pupil_right: 5
pupil_top: 7

# Face memory parameters.
face_memory_enabled: False # Overall on/off switch for tracking previous faces.
face_memory: 10 # How many faces should be "remembered" before a repeat is allowed.
tolerance: 0.4 # How likely to conclude "face seen before"

# Fraction of new face entering the morph.
new_face_fraction: 0.3

# Face criteria.
max_blur: 1000
max_head_yaw: 1000
max_head_pitch: 1000
max_head_roll: 1000
min_prob: 0.3
min_face_width: 200

# Intermediate face processing parameters. Probably don't need to change!
face_mesh_margin: 0.2
face_mesh_conf: 0.7
